version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
    depends_on:
      - mysqldb

  mysqldb:
    image: mariadb
    container_name: mysqldb
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo_db
    expose:
      - 3306
    ports:
      - "33060:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
