create SCHEMA IF NOT EXISTS demo_db;

USE demo_db;

DROP TABLE IF EXISTS person;

CREATE TABLE person (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  age INTEGER NOT NULL,
  PRIMARY KEY (id)
);

