spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:33060}/demo_db?&useSSL=FALSE&allowPublicKeyRetrieval=TRUE
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    datasource: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org:
      springframework.web: DEBUG
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder:
                debug
        EnumType:
          trace
